# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-LibXML-Enhanced
version:      0.01
version_from: lib/XML/LibXML/Enhanced.pm
installdirs:  perl
requires:
    Class::Singleton:              0
    Data::Eacherator:              0
    XML::LibXML:                   0
    XML::LibXSLT:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
